version: "3.8"
services:
  api:
    build: ./api
    container_name: api_container
    ports:
      - '4000:4000'
  myblog:
    build: ./myblog
    container_name: myblog_container
    ports:
      - '3000:3000'
    stdin_open: true  # both stdin and tty starts the container in interactive mode when set to true
    tty: true
